//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleListaCompra
    {
        public int DetalleListaCompraId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> ListaCompraId { get; set; }
        public decimal Precio { get; set; }
        public decimal Cantidad { get; set; }
    
        public virtual ListaCompra ListaCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
