//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliaCode
    {
        public FamiliaCode()
        {
            this.Inventario = new HashSet<Inventario>();
            this.ListaCompra = new HashSet<ListaCompra>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int FamiliaId { get; set; }
        public string FamiliaNombre { get; set; }
        public string FamiliaCodigo { get; set; }
    
        public virtual ICollection<Inventario> Inventario { get; set; }
        public virtual ICollection<ListaCompra> ListaCompra { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
