//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int InventarioId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public Nullable<int> UserId { get; set; }
        public decimal Cantidad { get; set; }
        public string Estado { get; set; }
    
        public virtual FamiliaCode FamiliaCode { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
