//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaCompra
    {
        public ListaCompra()
        {
            this.DetalleListaCompra = new HashSet<DetalleListaCompra>();
        }
    
        public int ListaCompraId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public string SupermercadoNombre { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<DetalleListaCompra> DetalleListaCompra { get; set; }
        public virtual FamiliaCode FamiliaCode { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
