//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Detail
    {
        public int LoginDetailId { get; set; }
        public Nullable<int> LoginId { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
