//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketOn.DataMarketOn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.DetalleListaCompra = new HashSet<DetalleListaCompra>();
            this.Inventario = new HashSet<Inventario>();
        }
    
        public int ProductoId { get; set; }
        public Nullable<int> CategoriaId { get; set; }
        public string ProductoNombre { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<DetalleListaCompra> DetalleListaCompra { get; set; }
        public virtual ICollection<Inventario> Inventario { get; set; }
    }
}
